/** 与原生 scene-dict-page/app.js generateMockRows 一致 */
export function generateMockRows() {
  return [
    {
      id: 1,
      nameCn: '圣诞节',
      nameEn: 'Christmas Day',
      type: 'holiday',
      level: 'S',
      seasonality: 'strong',
      countries: ['US', 'UK', 'DE', 'CA', 'AU'],
      skuPlan: 150,
      tags: ['爆款场景', '年度重点'],
      dateRule: { mode: 'fixed', month: 12, day: 25 },
      enabled: true,
    },
    {
      id: 2,
      nameCn: '万圣节',
      nameEn: 'Halloween',
      type: 'holiday',
      level: 'S',
      seasonality: 'strong',
      countries: ['US', 'UK', 'CA'],
      skuPlan: 120,
      tags: ['爆款场景'],
      dateRule: { mode: 'fixed', month: 10, day: 31 },
      enabled: true,
    },
    {
      id: 3,
      nameCn: '感恩节',
      nameEn: 'Thanksgiving Day',
      type: 'holiday',
      level: 'S',
      seasonality: 'strong',
      countries: ['US', 'CA'],
      skuPlan: 100,
      tags: ['爆款场景', '年度重点'],
      dateRule: { mode: 'relative', nth: 4, weekday: 4, month: 11 },
      enabled: true,
    },
    {
      id: 4,
      nameCn: '美国母亲节',
      nameEn: "Mother's Day (US)",
      type: 'holiday',
      level: 'A',
      seasonality: 'strong',
      countries: ['US', 'CA', 'AU'],
      skuPlan: 80,
      tags: ['长尾可卖'],
      dateRule: { mode: 'relative', nth: 2, weekday: 0, month: 5 },
      enabled: true,
    },
    {
      id: 5,
      nameCn: '美国父亲节',
      nameEn: "Father's Day (US)",
      type: 'holiday',
      level: 'A',
      seasonality: 'medium',
      countries: ['US', 'CA'],
      skuPlan: 60,
      tags: ['长尾可卖'],
      dateRule: { mode: 'relative', nth: 3, weekday: 0, month: 6 },
      enabled: true,
    },
    {
      id: 6,
      nameCn: '情人节',
      nameEn: "Valentine's Day",
      type: 'holiday',
      level: 'A',
      seasonality: 'strong',
      countries: ['US', 'UK', 'DE', 'AU', 'CA'],
      skuPlan: 90,
      tags: ['爆款场景'],
      dateRule: { mode: 'fixed', month: 2, day: 14 },
      enabled: true,
    },
    {
      id: 7,
      nameCn: '复活节',
      nameEn: 'Easter Sunday',
      type: 'holiday',
      level: 'A',
      seasonality: 'medium',
      countries: ['US', 'UK', 'DE', 'AU'],
      skuPlan: 55,
      tags: [],
      dateRule: {
        mode: 'manual',
        dates: { 2025: '2025-04-20', 2026: '2026-04-05', 2027: '2027-03-28' },
      },
      enabled: true,
    },
    {
      id: 8,
      nameCn: '新年元旦',
      nameEn: "New Year's Day",
      type: 'holiday',
      level: 'B',
      seasonality: 'strong',
      countries: ['US', 'UK', 'DE', 'CA', 'AU'],
      skuPlan: 40,
      tags: ['长尾可卖'],
      dateRule: { mode: 'fixed', month: 1, day: 1 },
      enabled: true,
    },
    {
      id: 9,
      nameCn: '美国独立日',
      nameEn: 'Independence Day (US)',
      type: 'holiday',
      level: 'B',
      seasonality: 'strong',
      countries: ['US'],
      skuPlan: 45,
      tags: [],
      dateRule: { mode: 'fixed', month: 7, day: 4 },
      enabled: true,
    },
    {
      id: 10,
      nameCn: '劳工节',
      nameEn: 'Labor Day (US)',
      type: 'holiday',
      level: 'B',
      seasonality: 'medium',
      countries: ['US', 'CA'],
      skuPlan: 30,
      tags: [],
      dateRule: { mode: 'relative', nth: 1, weekday: 1, month: 9 },
      enabled: true,
    },
    {
      id: 11,
      nameCn: '德国圣诞市场',
      nameEn: 'Weihnachtsmarkt Season',
      type: 'holiday',
      level: 'A',
      seasonality: 'strong',
      countries: ['DE'],
      skuPlan: 65,
      tags: ['欧洲市场'],
      dateRule: { mode: 'fixed', month: 12, day: 1 },
      enabled: true,
    },
    {
      id: 12,
      nameCn: '英国盒装日',
      nameEn: 'Boxing Day (UK)',
      type: 'holiday',
      level: 'B',
      seasonality: 'medium',
      countries: ['UK', 'AU', 'CA'],
      skuPlan: 35,
      tags: ['促销季'],
      dateRule: { mode: 'fixed', month: 12, day: 26 },
      enabled: true,
    },
    {
      id: 13,
      nameCn: '澳大利亚国庆日',
      nameEn: 'Australia Day',
      type: 'holiday',
      level: 'C',
      seasonality: 'weak',
      countries: ['AU'],
      skuPlan: 20,
      tags: [],
      dateRule: { mode: 'fixed', month: 1, day: 26 },
      enabled: true,
    },
    {
      id: 14,
      nameCn: '黑色星期五',
      nameEn: 'Black Friday',
      type: 'holiday',
      level: 'S',
      seasonality: 'strong',
      countries: ['US', 'UK', 'DE', 'CA', 'AU'],
      skuPlan: 200,
      tags: ['爆款场景', '年度重点', '促销季'],
      dateRule: { mode: 'relative', nth: 4, weekday: 5, month: 11 },
      enabled: true,
    },
    {
      id: 15,
      nameCn: '网络星期一',
      nameEn: 'Cyber Monday',
      type: 'holiday',
      level: 'S',
      seasonality: 'strong',
      countries: ['US', 'UK', 'CA'],
      skuPlan: 180,
      tags: ['爆款场景', '促销季'],
      dateRule: { mode: 'relative', nth: -1, weekday: 1, month: 11 },
      enabled: true,
    },
    {
      id: 16,
      nameCn: '美国总统日',
      nameEn: "Presidents' Day",
      type: 'holiday',
      level: 'C',
      seasonality: 'weak',
      countries: ['US'],
      skuPlan: 15,
      tags: [],
      dateRule: { mode: 'relative', nth: 3, weekday: 1, month: 2 },
      enabled: true,
    },
    {
      id: 17,
      nameCn: '圣帕特里克节',
      nameEn: "St. Patrick's Day",
      type: 'holiday',
      level: 'B',
      seasonality: 'medium',
      countries: ['US', 'UK', 'CA'],
      skuPlan: 35,
      tags: ['长尾可卖'],
      dateRule: { mode: 'fixed', month: 3, day: 17 },
      enabled: true,
    },
    {
      id: 18,
      nameCn: '阵亡将士纪念日',
      nameEn: 'Memorial Day (US)',
      type: 'holiday',
      level: 'B',
      seasonality: 'medium',
      countries: ['US'],
      skuPlan: 28,
      tags: [],
      dateRule: { mode: 'relative', nth: -1, weekday: 1, month: 5 },
      enabled: true,
    },
    {
      id: 19,
      nameCn: '美国返校季',
      nameEn: 'Back to School Season',
      type: 'holiday',
      level: 'A',
      seasonality: 'strong',
      countries: ['US', 'CA'],
      skuPlan: 85,
      tags: ['长尾可卖', '季节场景'],
      dateRule: { mode: 'fixed', month: 8, day: 15 },
      enabled: true,
    },
    {
      id: 20,
      nameCn: '英国母亲节',
      nameEn: 'Mothering Sunday (UK)',
      type: 'holiday',
      level: 'A',
      seasonality: 'strong',
      countries: ['UK'],
      skuPlan: 55,
      tags: [],
      dateRule: { mode: 'relative', nth: 4, weekday: 0, month: 3 },
      enabled: true,
    },
    {
      id: 21,
      nameCn: '宠物用品',
      nameEn: 'Pet Supplies',
      type: 'static',
      seasonAttr: 'annual',
      mainCategory: '宠物零食,宠物玩具,宠物服饰',
      countries: ['US', 'UK', 'DE', 'CA', 'AU'],
      skuPlan: 60,
      tags: ['长尾可卖'],
      level: null,
      seasonality: 'all_year',
      dateRule: null,
      enabled: true,
    },
    {
      id: 22,
      nameCn: '户外露营',
      nameEn: 'Outdoor Camping',
      type: 'static',
      seasonAttr: 'ss',
      mainCategory: '帐篷,睡袋,炊具,灯具',
      countries: ['US', 'CA', 'AU', 'DE'],
      skuPlan: 45,
      tags: ['季节场景'],
      level: null,
      seasonality: 'all_year',
      dateRule: null,
      enabled: true,
    },
    {
      id: 23,
      nameCn: '厨房烘焙',
      nameEn: 'Kitchen & Baking',
      type: 'static',
      seasonAttr: 'fw',
      mainCategory: '烤模,烘焙工具,围裙',
      countries: ['US', 'UK', 'DE'],
      skuPlan: 35,
      tags: ['长尾可卖'],
      level: null,
      seasonality: 'all_year',
      dateRule: null,
      enabled: true,
    },
    {
      id: 24,
      nameCn: '家庭健身',
      nameEn: 'Home Fitness',
      type: 'static',
      seasonAttr: 'annual',
      mainCategory: '瑜伽垫,哑铃,弹力带',
      countries: ['US', 'UK', 'CA', 'AU'],
      skuPlan: 50,
      tags: [],
      level: null,
      seasonality: 'all_year',
      dateRule: null,
      enabled: true,
    },
    {
      id: 25,
      nameCn: '婴儿护理',
      nameEn: 'Baby Care',
      type: 'static',
      seasonAttr: 'annual',
      mainCategory: '婴儿玩具,护肤,喂哺',
      countries: ['US', 'UK', 'DE', 'AU', 'CA'],
      skuPlan: 70,
      tags: ['长尾可卖', '年度重点'],
      level: null,
      seasonality: 'all_year',
      dateRule: null,
      enabled: true,
    },
  ]
}
